{
 "title": "Styx System Overview",
 "tags": [
  "Styx",
  "General"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU per phase (ms)",
   "type": "timeseries",
   "description": "The amount of CPU time consumed by each of the different transactional phases in ms",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(phase_cpu_ms_total[5s])",
     "legendFormat": "{{phase}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Ingress per phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(phase_net_rx_bytes_total[5s])",
     "legendFormat": "{{phase}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Egress per phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(phase_net_tx_bytes_total[5s])",
     "legendFormat": "{{phase}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "description": "System-wide CPU utilization",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (worker_cpu_usage_percent > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (worker_memory_usage_mb) * 1000000"
    }
   ]
  },
  {
   "title": "Ingress Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(worker_network_rx_kb[5s])) * 1000"
    }
   ]
  },
  {
   "title": "Egress Network (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(worker_network_tx_kb[5s])) * 1000"
    }
   ]
  },
  {
   "title": "Consumption Rate",
   "type": "timeseries",
   "description": "Rate of how many requests the workers consume from kafka (per second). This metric tries to approximate the input rate that is coming into styx, although it can be inaccurate when there is migration/slow epochs, as it will produce artificial spikes due to the workers consuming a lot more records in order to catch up.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(input_rate_counter_total[15s]))",
     "legendFormat": "Total Worker Consumption Rate"
    }
   ]
  },
  {
   "title": "TPS (committed)",
   "type": "timeseries",
   "description": "Throughput per epoch of the committed transactions",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(epoch_total_transactions_total[15s]))"
    }
   ]
  },
  {
   "title": "Backlog (Lag)",
   "type": "timeseries",
   "description": "Backlog - number of input elements that have been consumed by styx but not yet processed (lag)",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "targets": [
    { "expr": "sum(queue_backlog)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Commit & Abort Count",
   "type": "timeseries",
   "description": "Calculates the per-second average rate of the different types of commits and aborts for each epoch",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "rate(epoch_committed_lock_free_total[15s]) > 0",
     "legendFormat": "lock_free_commited ({{exported_instance}})"
    },
    {
     "expr": "rate(epoch_committed_fallback_total[15s])> 0",
     "legendFormat": "fallback_comitted ({{exported_instance}})"
    },
    {
     "expr": "rate(epoch_logic_aborts_total[15s]) > 0",
     "legendFormat": "logic_aborts ({{exported_instance}})"
    },
    {
     "expr": "rate(epoch_concurrency_aborts_total[15s]) > 0",
     "legendFormat": "concurrency_aborts ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Worker count",
   "type": "timeseries",
   "description": "Amount of active workers participating in the protocol",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "targets": [
    { "expr": "live_worker_count", "legendFormat": "Worker count" }
   ]
  },
  {
   "title": "Throughput Comparison",
   "type": "timeseries",
   "description": "Comparison of the incoming input rate across all workers vs the total output tps.\nIf lines divergence the system is not sustaining the incoming load.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(input_rate_counter_total[15s]))",
     "legendFormat": "Input Rate"
    },
    {
     "expr": "sum(rate(epoch_total_transactions_total[15s]))",
     "legendFormat": "Output Rate"
    }
   ]
  },
  {
   "title": "Average Latency Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(latency_breakdown > 0) by (component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "description": "Total latency of commited transactions",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(worker_epoch_latency_ms)" }
   ]
  },
  {
   "title": "Operator Execution time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (operator) (operator_latency_ms)",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "Average Operator Call Count ",
   "type": "timeseries",
   "description": "Number of times a call goes through an operator during the epoch per worker",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 21 },
   "targets": [
    {
     "expr": "(rate(operator_call_count_total[15s])) > 0",
     "legendFormat": "{{operator}} ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Worker Utilisation",
   "type": "timeseries",
   "description": "CPU Ratio - ratio of processing time to total epoch time. Calculated as latency needed for processing heavy phases divided by the total epoch time\nIO Ratio - similar but for IO",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(worker_cpu_utilization[5s]) * 100",
     "legendFormat": "CPU ({{exported_instance}})"
    },
    {
     "expr": "avg_over_time(worker_io_utilization[5s]) * 100",
     "legendFormat": "IO ({{exported_instance}})"
    }
   ]
  },
  {
   "title": "Snapshot Latency",
   "type": "timeseries",
   "description": "Total latency for taking a snapshot",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(worker_total_snapshotting_time_ms)"
    }
   ]
  },
  {
   "title": "Abort Rate (%)",
   "type": "timeseries",
   "description": "Percentage of aborted transactions",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(worker_abort_percent)" }
   ]
  },
  {
   "title": "Time since last heartbeat (ms)",
   "type": "bargauge",
   "description": "Time since the last heartbeat for each worker",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time_since_last_heartbeat", "legendFormat": "{{exported_instance}}" }
   ]
  }
 ]
}